steps:
# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']

# Image build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/linkme-example/practice-3:0.1', '.']

# Registry push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/linkme-example/practice-3:0.1']

# Deploy
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/my-deployment', 'practice-2-sha256=gcr.io/linkme-example/practice-3:0.1']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'