steps:
# Download dependancies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

# Test
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']

# Image build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/test-linkme/practice-3:0.2', '.']

# Registry push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-linkme/practice-3:0.2']

# Deploy
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/my-deployment', 'practice-2-sha256=gcr.io/test-linkme/practice-3:0.2']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'